### PR TITLE
raise lower bound to ocaml 4.08.0; remove rresult dependency

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Review by Leonidas-from-XIV — APPROVED** [review]
The code looks fine and given the signatures are compatible, it shouldn't cause incompatibilities.

I also agree that it 4.08 is probably fine but given it looks like there is not much work in keeping it 4.03 compatible (with the dune translation layer), maybe that would make sense?

**Comment by hannesm** [comment]
"not much work keeping 4.03" well, Result.bind is only available since 4.08. Are there any users with OCaml < 4.08?

And of course, there are random "shim" layers (such as result, stdlib-shims, ...) for stdlib extensions, but my experience is getting rid of them (in your dependency cone) is cumbersome.

Also, people with OCaml <4.08 can still install an old syslog-message release.

**Comment by Leonidas-from-XIV** [comment]
Ah right, I forgot that `Result.bind` needs 4.08 (though easy enough to implement).

I agree that getting shims for this is probably more of a headache than it is worth, especially as 4.08 is from 2019 and most people should be able to use it by now.

**Comment by verbosemode** [comment]
Thanks

**Pull request merged**
